export const mexicanStates = [
  // {value: 'aguascalientes', name: 'Aguascalientes', code: 'AGS'},
  {value: 'bajacalifornia', name: 'Baja California', code: 'BC'},
  {value: 'bajacaliforniasur', name: 'Baja California Sur', code: 'BCS'},
  // {value: 'campeche', name: 'Campeche', code: 'CAMP'},
  // {value: 'chiapas', name: 'Chiapas', code: 'CHIS'},
  {value: 'chihuahua', name: 'Chihuahua', code: 'CHIH'},
  // {value: 'cdmx', name: 'Ciudad de México', code: 'CDMX'},
  {value: 'coahuila', name: 'Coahuila', code: 'COAH'},
  // {value: 'colima', name: 'Colima', code: 'COL'},
  {value: 'durango', name: 'Durango', code: 'DGO'},
  // {value: 'guanajuato', name: 'Guanajuato', code: 'GTO'},
  // {value: 'guerrero', name: 'Guerrero', code: 'GRO'},
  // {value: 'hidalgo', name: 'Hidalgo', code: 'HGO'},
  // {value: 'jalisco', name: 'Jalisco', code: 'JAL'},
  // {value: 'mexico', name: 'México', code: 'MEX'},
  // {value: 'michoacan', name: 'Michoacán', code: 'MICH'},
  // {value: 'morelos', name: 'Morelos', code: 'MOR'},
  {value: 'nayarit', name: 'Nayarit', code: 'NAY'},
  {value: 'nuevoleon', name: 'Nuevo León', code: 'NL'},
  // {value: 'oaxaca', name: 'Oaxaca', code: 'OAX'},
  // {value: 'puebla', name: 'Puebla', code: 'PUE'},
  // {value: 'queretaro', name: 'Querétaro', code: 'QRO'},
  // {value: 'quintanaroo', name: 'Quintana Roo', code: 'QR'},
  // {value: 'sanluispotosi', name: 'San Luis Potosí', code: 'SLP'},
  {value: 'sinaloa', name: 'Sinaloa', code: 'SIN'},
  {value: 'sonora', name: 'Sonora', code: 'SON'},
  // {value: 'tabasco', name: 'Tabasco', code: 'TAB'},
  // {value: 'tamaulipas', name: 'Tamaulipas', code: 'TAM'},
  // {value: 'tlaxcala', name: 'Tlaxcala', code: 'TLAX'},
  // {value: 'veracruz', name: 'Veracruz', code: 'VER'},
  // {value: 'yucatan', name: 'Yucatán', code: 'YUC'},
  // {value: 'zacatecas', name: 'Zacatecas', code: 'ZAC'},
];
